EvaluacionV1/Models/ErrorViewModel.cs
namespace EvaluacionV1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EvaluacionV1/Controllers/HomeController.cs
using EvaluacionV1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ClassLibrary1;

namespace EvaluacionV1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewBag.ErrorMessage = "Llena todos los campos para poder iniciar secion";
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        public IActionResult Login (string NombreUsr, string ContraseñaUsr)
        {
            ProyectoEntities db = new ProyectoEntities();

            string user = NombreUsr;
            string pass = ContraseñaUsr;

            var puesto = (from p in db.Usuarios where p.NombreUsr == user && p.ContraseñaUsr == pass select p.IdUser).FirstOrDefault();

            //ViewBag.test = "hola";

            if (string.IsNullOrEmpty(NombreUsr) && string.IsNullOrEmpty(ContraseñaUsr))
            {
                ViewBag.ErrorMessage = "Llena todos los campos para poder iniciar secion";
                return RedirectToAction("Index", "Home");
            }
            else
            {
                if (puesto == 1)
                {
                    return RedirectToAction("Index", "JefeComputo");

                }
                else if (puesto == 2)
                {
                    return RedirectToAction("Index", "JefeArea");
                }
                else
                {
                    return RedirectToAction("Privacy", "Home");
                }
            }

            
        }
    }
}

EvaluacionV1/Controllers/JefeAreaController.cs
using ClassLibrary1;
using Microsoft.AspNetCore.Mvc;
using Negocio;

namespace EvaluacionV1.Controllers
{
    public class JefeAreaController : Controller
    {

        Class1 reportes = new Class1();
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddReport()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddReporte(ClassLibrary1.Reportes itm)
        {
            reportes.Agregar(itm);
            return RedirectToAction("Index");
        }

        public IActionResult LastDetails(int IdReporte)
        {
            return View(reportes.Buscar(IdReporte));
        }

        public IActionResult ListR()
        {
            return View(reportes.ListarReportes());
        }

    }
}

EvaluacionV1/Controllers/JefeComputoController.cs
using ClassLibrary1;
using Microsoft.AspNetCore.Mvc;
using Negocio;
namespace EvaluacionV1.Controllers
{
    public class JefeComputoController : Controller
    {
        Class1 reporte = new Class1();
        public IActionResult Index()
        {
            return View(reporte.ListarReportes());
        }

        public ActionResult EditReport(int IdReporte)
        {
            return View(reporte.Buscar(IdReporte));
        }

        [HttpPost]
        public ActionResult EditReport(ClassLibrary1.Reportes itm)
        {
            reporte.Modificar(itm);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteReport(int IdReporte)
        {
            return View(reporte.Buscar(IdReporte));
        }
        [HttpPost]
        public ActionResult DeleteReporte(int IdReporte)
        {
            reporte.Eliminar(IdReporte);

            return RedirectToAction(nameof(Index));
        }
    }
}

EvaluacionV1/Controllers/ReportesController.cs
using Microsoft.AspNetCore.Mvc;
using Negocio;

namespace EvaluacionV1.Controllers
{
    public class ReportesController : Controller
    {
        Class1 reportes = new Class1();
        public IActionResult Index()
        {
            return View(reportes.ListarReportes());
        }

        public IActionResult AddReport()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddReporte(ClassLibrary1.Reportes itm)
        {
            reportes.Agregar(itm);
            return RedirectToAction("Index");
        }

        public IActionResult DetailsReport(int IdReporte)
        {
            return View(reportes.Buscar(IdReporte));
        }

        public ActionResult EditReport(int IdReporte)
        {
            return View(reportes.Buscar(IdReporte));
        }

        [HttpPost]
        public ActionResult EditReport(ClassLibrary1.Reportes itm)
        {
            reportes.Modificar(itm);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteReport(int IdReporte)
        {
            return View(reportes.Buscar(IdReporte));
        }
        [HttpPost]
        public ActionResult DeleteReporte(int IdReporte)
        {
            reportes.Eliminar(IdReporte);

            return RedirectToAction(nameof(Index));
        }

    }
}

EvaluacionV1/Controllers/RolesController.cs
using Microsoft.AspNetCore.Mvc;
using Negocio;

namespace EvaluacionV1.Controllers
{
    public class RolesController : Controller
    {
        Class1 roles = new Class1();
        public IActionResult Index()
        {
            return View(roles.ListarRoles());
        }
    }
}

EvaluacionV1/Controllers/TrabajadoresController.cs
using Microsoft.AspNetCore.Mvc;
using Negocio;

namespace EvaluacionV1.Controllers
{
    public class TrabajadoresController : Controller
    {
        Class1 trabajadores =new Class1();
        public IActionResult Index()
        {
            return View(trabajadores.ListarTrabajadores());
        }
    }
}

EvaluacionV1/Views/Home/Index.cshtml
@model ClassLibrary1.Usuarios
@{
    ViewData["Title"] = "Inicio de sesion";
}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<div class="text-center bg-dark">
    <img src="./iniciar-sesion.png" class="mt-3"/>
    <h1 class="display-4 text-light h1">Inicio de sesion</h1>

    @using (Html.BeginForm("Login", "Home", FormMethod.Post))
    {
        <div class="divLog">
            <p class="text-light h3 plog">Nombre de usuario</p>
            <input class="form-control inpLog" placeholder="Usuario" id="NombreUsr" name="NombreUsr" />
        </div>
        <div class="divLog mt-3">
            <p class="text-light h3 plog2">Constraseña</p>
            <input class="form-control inpLog" placeholder="Contraseña" type="password" id="ContraseñaUsr" name="ContraseñaUsr" />
        </div>

        <div class="mt-5">
            <button type="submit" class="btn btn-light px-5"> Inicio de sesion </button>
        </div>
    }
</div>

<!--
    <script type="text/javascript">
    Swal.fire(
        '@ViewBag.ErrorMessage',
        '',
        'success');

    console.log(@ViewBag.ErrorMessage);
    </script>
-->

EvaluacionV1/Views/JefeArea/AddReport.cshtml
@model ClassLibrary1.Reportes

@{
    ViewData["Title"] = "AddReport";
}

<h1 class="text-light">Agregar un nuevo reporte</h1>

<h4 class="text-light">Reportes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddReporte">
            <div class="form-group">
                <label class="control-label text-light">ID</label>
                <input asp-for="IdReporte" class="form-control" placeholder="Eje. 1"/>
            </div>
            <div class="form-group">
                <label class="control-label text-light">Equipo</label>
                <input asp-for="Equipo" class="form-control" placeholder="Eje. PC" />

            </div>
            <div class="form-group">
                <label class="control-label text-light">Accion a realizar</label>
                <input asp-for="AccionRealizar" class="form-control" placeholder="Eje. Formateo" />
            </div>
            <div class="form-group">
                <label class="control-label text-light">Atencion</label>
                <input asp-for="Atencion" class="form-control" placeholder="Eje. Interno" />
            </div>
            <div class="form-group mt-3 mb-2">
                <input type="submit" value="Agregar Ticket" class="btn btn-primary" />
            </div>
            <a class="btn btn-warning text-dark" asp-action="Index">Volver a la pagina principal</a>
        </form>
        
    </div>
    
</div>

EvaluacionV1/Views/JefeArea/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="text-center text-light mt-5 mb-3">
    <div >
        <h1>Jefe del área verificada</h1>

        <h4>¿Tienes algun problema?</h4>

        <img src="./error.png" class="my-3" />

    </div>

    <div class="buttons">
        <a class="btn btn-primary mt-5" asp-area="" asp-controller="JefeArea" asp-action="AddReport">Abrir un nuevo ticket de asistencia</a>

        <a class="btn btn-primary mt-5" asp-area="" asp-controller="JefeArea" asp-action="ListR">Ver tickets de asistencia abiertos</a>
    </div>
</div>

EvaluacionV1/Views/JefeArea/LastDetails.cshtml
@model ClassLibrary1.Reportes

@{
    ViewData["Title"] = "DetailsReport";
}

<h2>Detalles del reporte</h2>

<table class="table text-light">
    <thead>
        <tr>
            <th>ID</th>
            <th>Equipo</th>
            <th>Accion a realizar</th>
            <th>Atencion</th>
        </tr>
    </thead>

    <tr>
        <td>
            @Html.DisplayFor(model => model.IdReporte)
        </td>
        <td>
            @Html.DisplayFor(model => model.Equipo)
        </td>
        <td>
            @Html.DisplayFor(model => model.AccionRealizar)
        </td>
        <td>
            @Html.DisplayFor(model => model.Atencion)
        </td>
    </tr>
</table>
<a class="btn btn-warning text-dark" asp-action="Index">Volver a la pagina principal</a>
<a class="btn btn-primary text-light" asp-action="ListR">Volver a la lista</a>

EvaluacionV1/Views/JefeArea/ListR.cshtml
@model List<ClassLibrary1.Reportes>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "ListR";
}

<div class="bg-dark text-light mt-4">
    <h2>Lista de reportes abiertos</h2>

    <hr />

    <table class="table text-light">
        <thead>
            <tr>
                <th>ID</th>
                <th>Equipo</th>
                
            </tr>
        </thead>


        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.IdReporte
                </td>
                <td>
                    @item.Equipo
                </td>
                <td>
                    <div class="btn btn-primary">
                        <a class="text-dark link1"> @Html.ActionLink("Detalles", "LastDetails", new { IdReporte = item.IdReporte })</a>
                    </div>
                </td>

            </tr>
        }

    </table>
    <a class="btn btn-warning text-dark" asp-action="Index">Volver a la pagina principal</a>
</div>

EvaluacionV1/Views/JefeComputo/DeleteReport.cshtml
@model ClassLibrary1.Reportes

@{
    ViewData["Title"] = "DeleteReport";
}

<h1 class="text-light">Aceptar y cerrar reporte</h1>


<h3 class="text-light">¿Esta seguro de querer cerrar el reporte?</h3>

<dl class="mt-3">
    <dd>
        <h2 class="text-light">
            ID
        </h2>

    </dd>
    <dd class="col-sm-10">
        <h5 class=" form-control">
            @Html.DisplayFor(model => model.IdReporte)
        </h5>

    </dd>
    <dd>
        <h2 class="text-light">
            Equipo
        </h2>

    </dd>
    <dd class="col-sm-10">
        <h5 class=" form-control">
            @Html.DisplayFor(model => model.Equipo)
        </h5>

    </dd>
    <dd>
        <h2 class="text-light">
            Accion a realizar
        </h2>

    </dd>
    <dd class="col-sm-10">
        <h5 class=" form-control">
            @Html.DisplayFor(model => model.AccionRealizar)
        </h5>

    </dd>
    <dd>
        <h2 class="text-light">
            Atencion
        </h2>

    </dd>
    <dd class="col-sm-10">
        <h5 class=" form-control">
            @Html.DisplayFor(model => model.Atencion)
        </h5>

    </dd>

</dl>

<form asp-action="DeleteReporte">
    <input type="hidden" asp-for="IdReporte" />
    <input type="submit" value="Cerrar Reporte" class="btn btn-danger" />
    <div>
        <a class="btn btn-light mt-3 text-dark" asp-action="Index">Regresar al listado</a>
    </div>
</form>

EvaluacionV1/Views/JefeComputo/EditReport.cshtml
@model ClassLibrary1.Reportes

<div >
    <h2 class="text-light mb-4 mt-5">Editar reporte</h2>

    @using (Html.BeginForm())
    {
        <table>
            <tr class="m-3">
                <td class="text-light">Equipo</td>
                <td>@Html.EditorFor(model => model.Equipo, new { htmlAttributes = new { @class = "form-control", placeholder = "Eje. PC" } })</td>
            </tr>
            <tr class="m-3">
                <td class="text-light">Accion a realizar</td>
                <td>@Html.EditorFor(model => model.AccionRealizar, new { htmlAttributes = new { @class = "form-control", placeholder = "Eje. Mantenimiento"} })</td>
            </tr>
            <tr class="m-3">
                <td class="text-light">Atencion</td>
                <td>@Html.EditorFor(model => model.Atencion, new { htmlAttributes = new { @class = "form-control", placeholder = "Eje. Externo" } })</td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input type="submit" value="Editar Registro" class="btn btn-success" />
                    <a class="btn btn-warning text-dark" asp-action="Index">Volver a la lista</a>
                </td>

            </tr>
        </table>
    }
</div>

EvaluacionV1/Views/JefeComputo/Index.cshtml
@model List<ClassLibrary1.Reportes>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="text-center text-light">
    <h1 >Bienvenido Jefe del centro de computo </h1>

    <h4> Tickets por revisar </h4>

    <hr />
    <table class="table text-light">
        <thead>
            <tr>
                <th>ID</th>
                <th>Equipo</th>
                <th>Accion a realizar</th>
                <th>Atencion</th>
            </tr>
        </thead>


        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.IdReporte
                </td>
                <td>
                    @item.Equipo
                </td>
                <td>
                    @item.AccionRealizar
                </td>
                <td>
                    @item.Atencion
                </td>
                <td>
                    <div class="btn btn-primary">
                        <a>@Html.ActionLink("Editar", "EditReport", new { IdReporte = item.IdReporte })</a>
                    </div>
                    <div class="btn btn-success">
                        <a>@Html.ActionLink("Aceptar", "DeleteReport", new { IdReporte = item.IdReporte })</a>
                    </div>
                </td>

            </tr>
        }

    </table>
    <hr />
    <a class="btn btn-primary btnUsr" asp-area="" asp-controller="Trabajadores" asp-action="Index">Usuarios</a>
</div>

EvaluacionV1/Views/Reportes/AddReport.cshtml
@model ClassLibrary1.Reportes

@{
    ViewData["Title"] = "AddReport";
}

<h1 class="text-light">Agregar un nuevo reporte</h1>

<h4 class="text-light">Reportes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddReporte">
            <div class="form-group">
                <label class="control-label text-light">ID</label>
                <input asp-for="IdReporte" class="form-control" placeholder="Eje. 1"/>
            </div>
            <div class="form-group">
                <label class="control-label text-light">Equipo</label>
                <input asp-for="Equipo" class="form-control" placeholder="Eje. PC" />

            </div>
            <div class="form-group">
                <label class="control-label text-light">Accion a realizar</label>
                <input asp-for="AccionRealizar" class="form-control" placeholder="Eje. Formateo" />
            </div>
            <div class="form-group">
                <label class="control-label text-light">Atencion</label>
                <input asp-for="Atencion" class="form-control" placeholder="Eje. Interno" />
            </div>
            <div class="form-group mt-3 mb-2">
                <input type="submit" value="Agregar Reporte" class="btn btn-primary"  />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-warning text-dark" asp-action="Index">Volver a la lista</a>
</div>

EvaluacionV1/Views/Reportes/DeleteReport.cshtml
@model ClassLibrary1.Reportes

@{
    ViewData["Title"] = "DeleteReport";
}

<h1 class="text-light">Cerrar reporte</h1>


<h3 class="text-light">¿Esta seguro de querer cerrar el reporte?</h3>

<dl class="mt-3">
    <dd>
        <h2 class="text-light">
            ID
        </h2>

    </dd>
    <dd class="col-sm-10">
        <h5 class=" form-control">
            @Html.DisplayFor(model => model.IdReporte)
        </h5>

    </dd>
    <dd>
        <h2 class="text-light">
            Equipo
        </h2>

    </dd>
    <dd class="col-sm-10">
        <h5 class=" form-control">
            @Html.DisplayFor(model => model.Equipo)
        </h5>

    </dd>
    <dd>
        <h2 class="text-light">
            Accion a realizar
        </h2>

    </dd>
    <dd class="col-sm-10">
        <h5 class=" form-control">
            @Html.DisplayFor(model => model.AccionRealizar)
        </h5>

    </dd>
    <dd>
        <h2 class="text-light">
            Atencion
        </h2>

    </dd>
    <dd class="col-sm-10">
        <h5 class=" form-control">
            @Html.DisplayFor(model => model.Atencion)
        </h5>

    </dd>

</dl>

<form asp-action="DeleteReporte">
    <input type="hidden" asp-for="IdReporte" />
    <input type="submit" value="Cerrar Reporte" class="btn btn-danger" />
    <div>
        <a class="btn btn-light mt-3 text-dark" asp-action="Index">Regresar al listado</a>
    </div>
</form>

EvaluacionV1/Views/Reportes/DetailsReport.cshtml
@model ClassLibrary1.Reportes

@{
    ViewData["Title"] = "DetailsReport";
}

<h2>Detalles del reporte</h2>

<table class="table text-light">
    <thead>
        <tr>
            <th>ID</th>
            <th>Equipo</th>
            <th>Accion a realizar</th>
            <th>Atencion</th>
        </tr>
    </thead>

        <tr>
            <td>
                @Html.DisplayFor(model => model.IdReporte)
            </td>
            <td>
                @Html.DisplayFor(model => model.Equipo)
            </td>
            <td>
                @Html.DisplayFor(model => model.AccionRealizar)
            </td>
            <td>
                @Html.DisplayFor(model => model.Atencion)
            </td>
        </tr>
</table>
<div>
    <div class="btn btn-primary text-dark">
        @Html.ActionLink("Editar registro", "EditReport", new { IdReporte = Model.IdReporte })
    </div>
    <a class="btn btn-warning text-dark" asp-action="Index">Volver a la lista</a>
</div>

EvaluacionV1/Views/Reportes/EditReport.cshtml
@model ClassLibrary1.Reportes

<div >
    <h2 class="text-light mb-4 mt-5">Editar reporte</h2>

    @using (Html.BeginForm())
    {
        <table>
            <tr class="m-3">
                <td class="text-light">Equipo</td>
                <td>@Html.EditorFor(model => model.Equipo, new { htmlAttributes = new { @class = "form-control", placeholder = "Eje. PC" } })</td>
            </tr>
            <tr class="m-3">
                <td class="text-light">Accion a realizar</td>
                <td>@Html.EditorFor(model => model.AccionRealizar, new { htmlAttributes = new { @class = "form-control", placeholder = "Eje. Mantenimiento"} })</td>
            </tr>
            <tr class="m-3">
                <td class="text-light">Atencion</td>
                <td>@Html.EditorFor(model => model.Atencion, new { htmlAttributes = new { @class = "form-control", placeholder = "Eje. Externo" } })</td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input type="submit" value="Editar Registro" class="btn btn-success" />
                    <a class="btn btn-warning text-dark" asp-action="Index">Volver a la lista</a>
                </td>

            </tr>
        </table>
    }
</div>

EvaluacionV1/Views/Reportes/Index.cshtml
@model List<ClassLibrary1.Reportes>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "Index";
}

<div class="bg-dark text-light mt-4">
    <h2>Lista de Reportes</h2>

    <a class="btn btn-warning text-dark" asp-action="AddReport">Abrir un ticket</a>

    <hr />
    <table class="table text-light">
        <thead>
            <tr>
                <th>ID</th>
                <th>Equipo</th>
                <th>Accion a realizar</th>
                <th>Atencion</th>
            </tr>
        </thead>


        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.IdReporte
                </td>
                <td>
                    @item.Equipo
                </td>
                <td>
                    @item.AccionRealizar
                </td>
                <td>
                    @item.Atencion
                </td>
                <td>
                    <div class="btn btn-primary">
                        <a class="text-dark link1"> @Html.ActionLink("Detalles", "DetailsReport", new { IdReporte = item.IdReporte })</a>
                    </div>
                    <div class="btn btn-primary">
						<a>@Html.ActionLink("Editar", "EditReport", new { IdReporte = item.IdReporte })</a>
					</div>
                    <div class="btn btn-danger">
						<a>@Html.ActionLink("Eliminar", "DeleteReport", new { IdReporte = item.IdReporte })</a>
					</div>
                </td>

            </tr>
        }

    </table>
</div>

EvaluacionV1/Views/Roles/Index.cshtml
@model List<ClassLibrary1.Roles>

@{
    ViewBag.Title = "Index";
}

<div class="bg-dark text-light mt-4">
    <h2>Lista de Roles</h2>

    <hr />
    <table class="table text-light">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
            </tr>
        </thead>


        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.IdRol
                </td>
                <td>
                    @item.NombreRol
                </td>

            </tr>
        }

    </table>
</div>

EvaluacionV1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EvaluacionV1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EvaluacionV1.styles.css" asp-append-version="true" />
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">EvaluacionV1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Ayuda</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container bg-dark ">
        <main role="main" class="pb-3 bg-dark alineado">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted  bg-dark">
        <div class="container  bg-dark">
            &copy; 2022 - Evaluacion V1 - 
            <a href="https://github.com/DavidPeralta36" style="color:#fff">Peralta Avila David Leonardo</a>
            <label class="text-light"> - 19470212</label>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EvaluacionV1/Views/Trabajadores/Index.cshtml
@model List<ClassLibrary1.Trabajadores>

@{
    ViewBag.Title = "Index";
}

<div class="bg-dark text-light mt-4">
    <h2>Lista de Trabajadores</h2>

    <hr />
    <table class="table text-light">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Apellido Paterno</th>
                <th>Apellido Materno</th>
                <th>Rol Asignado</th>
            </tr>
        </thead>


        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.IdTrabajador
                </td>
                <td>
                    @item.Nombre
                </td>
                <td>
                    @item.Apaterno
                </td>
                <td>
                    @item.Amaterno
                </td>
                <td>
                    @item.Rol
                </td>
            </tr>
        }

    </table>
    <hr />
    <a class="btn btn-primary" asp-area="" asp-controller="JefeComputo" asp-action="Index">Volver a la vista principal</a>
</div>